# Generated by Django 3.1 on 2020-09-01 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('vinnumber', models.CharField(max_length=50, null=True, unique=True)),
                ('dateofpurchase', models.DateTimeField(blank=True, null=True)),
                ('dateoflastservice', models.DateTimeField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=10, null=True)),
                ('capacity', models.CharField(blank=True, max_length=2, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='clients.client')),
            ],
        ),
    ]
